### ISSUE TITLE
[Suggestion] Send to chat (like a normal compendium roll)

### ISSUE THREAD

**Issue by kinland** [DiceT/tabletags#1]
I've set up two `1d10000` tables of random effects, and wanted to use tabletags to essentially roll a `1d20000`. Foundry in general seems to struggle with the size of these tables if you open the GUI by accident, so breaking up into multiple tables and using tabletags sounded like a great idea.

Unfortunately, it looks like tabletags only sends the results to the place the macro was executed, so you don't get the nice chat card or see die rolls, etc.

**Comment by DiceT** [comment]
Tabletags does return a string of the results that you can push as a chat message. Does this answer that question?

Also, as long as you don't roll in silent mode, there should be a table roll visible in chat. For instance, when I roll the below macro, I get two chat messages. Maybe I am not understanding something here...?

```
let result = await TableTagsAPI.TableTagRoller(["Dungeon Dressing"]);
 
ChatMessage.create({
  user: game.user._id,
  speaker: ChatMessage.getSpeaker({token: actor}),
  content: result
});
```

![image](https://user-images.githubusercontent.com/84727873/169253283-b9aa7301-c575-426f-bbc9-42ac747f32c4.png)
